project:
  type: website
  output-dir: docs

website:
  favicon: images/logo.jpg
  title: "Francois Duchenne"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About my research
      - href: community.qmd
        text: Community Ecology
      - href: globalchange.qmd
        text: Global change & Biodiversity

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

