project:
  type: website
  output-dir: docs

website:
  favicon: images/logo.png
  title: "François Duchenne"
  site-url: 'https://f-duchenne.github.io/francoisduchenne.github.io'
  site-path: '/'
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About my research
      - href: community.qmd
        text: Community Ecology
      - href: globalchange.qmd
        text: Global change & Biodiversity
      - href: publications.qmd
        text: CV & Publications

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

