---
title: "Publications"
---

All my publications are listed on my [Google Sholar profile](https://scholar.google.ch/citations?user=FkZF-4sAAAAJ&hl=en).

All my publications, including my PhD thesis, are [available here](https://www.google.com/url?q=https%3A%2F%2Fhal.archives-ouvertes.fr%2Fsearch%2Findex%2F%3Fq%3D%252A%26authFullName_s%3DFran%25C3%25A7ois%2BDuchenne&sa=D&sntz=1&usg=AOvVaw0dRglBdnHW8vjFee1vn7ii) in open access.

# Recent publications

[A probabilistic view of forbidden links: their prevalence and their consequences for the robustness of mutualistic networks](https://doi.org/10.1101/2024.07.04.602032). (submitted) François Duchenne, Elisa Barreto, Esteban A. Guevara, Holger Beck, Carolina Bello, Rafaela Bobato, Daniela Bôlla, Emanuel Brenes, Nicole Büttner, Ana P. Caron, Nelson Chaves-Elizondo, María J. Gavilanes, Alejandro Restrepo-González, Jose Alejandro Castro, Miriam Kaehler, Tiago Machado-de-Souza, Miguel Machnicki-Reis, Andrés Sebastián F. Marcayata, Cauã G. de Menezes^5^, Andrea Nieto, Rafael de Oliveira, Ricardo A. C. de Oliveira, Friederike Richter, Bryan G. Rojas, Luciele L. Romanowski, Wellinton L.de Souza, Danila S. Veluza, Ben Weinstein, Rafael Wüest, Thais B. Zanata, Krystal Zuniga, María A. Maglianesi, Tatiana Santander, Isabella G. Varassin & Catherine H. Graham. *bioRxiv*

Weather explains inter-annual variability, but not the temporal decline, in insect biomass. (in press) F. Duchenne & C. Fontaine. *Insect Conservation and Diversity*

[Macroevolution of the plant--hummingbird pollination system](https://doi.org/10.1111/brv.13094). (2024) Barreto, E., Boehm, M.M.A., Ogutcen, E., Abrahamczyk, S., Kessler, M., Bascompte, J., Dellinger, A.S., Bello, C., Dehling, D.M., Duchenne, F., Kaehler, M., Lagomarsino, L.P., Lohmann, L.G., Maglianesi, M.A., Morlon, H., Muchhala, N., Ornelas, J.F., Perret, M., Salinas, N.R., Smith, S.D., Vamosi, J.C., Varassin, I.G. and Graham, C.H.. *Biological Reviews*

[When cheating turns into a stabilizing mechanism of plant--pollinator communities](https://doi.org/10.1371/journal.pbio.3002434). (2023) F. Duchenne, S. Aubert, E. Barreto, E. Brenes, M. A. Maglianesi, T. Santander, E. Guevara & C. H. Graham. *Plos Biology* 21 (12), e3002434

[Seasonal structure of interactions enhances multidimensional stability of mutualistic networks](https://doi.org/10.1098/rspb.2022.0064) (2022) F. Duchenne, R. O. Wüest, C. H. Graham. *Proceedings of the Royal Society B* 289 (1982), 20220064
